### ISSUE TITLE
5V Pin on PWM

### ISSUE THREAD

**Issue by flamespinner** [hatsunearu/arduino-victor888-controller#1]
You do Need the 5v PWM Pin plugged into a pin on the arduino if you are going to be using a PWM Splitter. Please note this in your read me. I Was using a PWM splitter off of one pin, and because it provides the Victors with less than 5v off of the arduino pin (Right around 3.3 v per Victor). This is not enough to supply a usable PWM signal to the victor. I added 5v to the PWM cable and it worked perfectly.  I would venture to guess that the Victor draws from the 5v rail on the PWM cable for extra power if the PWM signal isn't 5v. Or something like that. But please note that you need the 5v Rail if you are are using a PWM splitter.

I fixed this by just setting a pin to HIGH in Void Setup

**Comment by hatsunearu** [comment]
That's really strange. It's been 3 years since I last tested this setup, but I vaguely remember not needing the Vcc pin on the Victor PWM connector. And it makes sense not to have that; the control electronics in the Victor is powered through the 12V motor bus.

If I'm reading your post correctly, I'm guessing you had a 3.3V PWM signal, which didn't work, but if you provide 5V to the V+ pin on the Victor PWM connector, that works?

**Comment by hatsunearu** [comment]
Commit 4dbc2d95e663b9550e6fdb079473bfadafc2c4dd should address this.

**Comment by flamespinner** [comment]
That is correct. I don't need the VCC pin if i'm just running one victor, I would venture to guess that is because its getting a full 5v signal that its suppose to be getting over PWM. But if i'm splitting it off of one pin, to two victors it dosn't have that 5v. So maybe it pulls from the VCC pin the power it needs to have the full 5v PWM Waveform?

**Comment by flamespinner** [comment]
Also, You wrote VDD not VCC...

**Comment by hatsunearu** [comment]
Ah... I think I know what's going on.
Looks like the Victor is being parasitically powered using the ESD protection diode/parasitic diode through the PWM pin, if Vcc is not powered. If you're wondering what this is, here is [a great video by EEVBlog about this issue](https://www.youtube.com/watch?v=2yFh7Vv0Paw).

I'm going to update the readme once more to address this point.

It's really VDD, VDD is for CMOS (~= Digital) circuits, like the Arduino and the Victor.

**Comment by hatsunearu** [comment]
Updated readme with this commit: 498235f488eb3979c5bcef0f959928165a6f045c

Basically what's happening is the entire control circuitry inside the Victor got powered through the PWM pin. The PWM pin can't supply a lot of current, so when two Victors started drawing from the same PWM pin, the PWM pin voltage sagged, which causes all sorts of unreliability issues.

Thanks for letting me know about this issue! I didn't come across this issue 3 years ago because I had separate PWM pins for each Victor.

Feel free to comment again if you encounter any other issues or come across evidence that my diagnosis is incorrect.
